---

services:
  vault:
    image: ${IMAGE}
    container_name: vault
    hostname: vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/var/atlassian/application-data/jira
      - vault_nginx_conf:/data/nginx
    environment:
      TZ: ${EKB}
      LE_FQDN: ${FQDN}
      CONTAINER_ALIAS: ${C_ALIAS}
      SERVER_ALIAS: ${S_ALIAS}
      # VAULT_DEV_ROOT_TOKEN_ID: ${URL_CONTEXTPATH}
    networks:
      - vault
      - nginx


volumes:
  vault_data:
    external: true
  vault_nginx_conf:
    external: true

networks:
  nginx:
    external: true
  vault:
    external: true
